# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#0e0e0e

# Main text color
theme[main_fg]=#e6e6e6

# Title color for boxes
theme[title]=#e6e6e6

# Highlight color for keyboard shortcuts
theme[hi_fg]=#c6c6c6

# Background color of selected item in processes box
theme[selected_bg]=#191919

# Foreground color of selected item in processes box
theme[selected_fg]=#c6c6c6

# Color of inactive/disabled text
theme[inactive_fg]=#757575

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#fbf9f0

# Background color of the percentage meters
theme[meter_bg]=#757575

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#fbf9f0

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#e8b59b
theme[mem_box]=#e4e3a6
theme[net_box]=#d1bc97
theme[proc_box]=#95c9a8

# Box divider line and small boxes line color
theme[div_line]=#484848

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#e4e3a6
theme[temp_mid]=#f7f0e3
theme[temp_end]=#d5ae68

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#dee3b8
theme[cpu_mid]=#bcce9b
theme[cpu_end]=#acd5c8

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#e8b59b
theme[free_mid]=#acd5c8
theme[free_end]=#95c9a8

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#bcce9b
theme[cached_mid]=#95c9a8
theme[cached_end]=#acd5c8

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#dccca6
theme[available_mid]=#d1bc97
theme[available_end]=#d5ae68

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#e4e3a6
theme[used_mid]=#dee3b8
theme[used_end]=#d6e0b2

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#dccca6
theme[download_mid]=#d1bc97
theme[download_end]=#d5ae68

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#e4e3a6
theme[upload_mid]=#dee3b8
theme[upload_end]=#d6e0b2

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#bcce9b
theme[process_mid]=#acd5c8
theme[process_end]=#e8b59b
